jobs:
  - name: alpha
    type: runSh
    steps:
      - IN: runImageIN
      - OUT: runImageOUT
      - TASK:
        - script: sudo apt-get install tree
        - pwd
    on_success:
      - script: echo 'This block executes after TASK section executes successfully'
      - NOTIFY: slack
    on_failure:
      - script: echo 'This block executes after TASK section fails'
      - NOTIFY: slack
      
  - name: bravo
    type: manifest
    steps:
      - IN: runImageIN
      - TASK: managed
    on_success:
      - script: echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - script: echo 'this is on_failure step of dv-man of type manifest'
    flags:
      - run

  - name: charlie
    type: runSh
    steps:
      - IN: sample-script
      - IN: runImageIN
      - TASK:
        - script: sudo apt-get install tree
        - pwd
        - script: tree -F IN
        - script: IN/sample-script-dup/gitRepo/echo.sh
 
  - name: delta
    type: deploy
    steps:
      - IN: bravo
      - TASK: managed
        deployMethod: upgrade
        
  - name: tango
    type: manifest
    steps:
      - IN: dv-image
        pull: false
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
    on_success:
      - script: echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - script: echo 'this is on_failure step of dv-man of type manifest'
    flags:
      - dv

  - name: xray
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionName: latest
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed

  - name: dv-man-versionNumber
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionNumber: 1
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed

  - name: box-man
    type: manifest
    steps:
      - IN: box-image
        pull: false
      - IN: box-opts
      - IN: box-params
      - TASK: managed
    flags:
      - box

  - name: box-test
    type: deploy
    steps:
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade
